apiVersion: v1
kind: Pod
metadata:
  name: nginx-dev
  labels:
    app: nginx-dev
  namespace: dev-cli
spec:
  containers:
    - name: nginx-dev
      image: nginx:alpine
      ports:
      - containerPort: 80
