- name: Update apt cache
  apt:
    update-cache: true
  become: true
- name: Install Docker
  apt:
    name: docker.io
  become: true
- name: Add user to Docker group
  user:
    name: yourname
    groups: docker
    append: true
  become: true
